### ISSUE TITLE
Please tag new release

### ISSUE THREAD

**Issue by ruudk** [symplify/github-actions#14]

**Comment by TomasVotruba** [comment]
There you go https://github.com/symplify/github-actions/releases/tag/0.1.2

**Comment by ruudk** [comment]
Tag doesn't show up here... https://github.com/symplify/monorepo-split-github-action

**Comment by TomasVotruba** [comment]
Hmm, the latest tag is resolved to previous one:
https://github.com/symplify/github-actions/runs/1491326330?check_suite_focus=true#step:4:108

I'll create an issue on https://github.com/WyriHaximus/github-action-get-previous-tag

**Comment by TomasVotruba** [comment]
Created https://github.com/WyriHaximus/github-action-get-previous-tag/issues/9

**Comment by ruudk** [comment]
Instead of doing it like this, can't you listen to the tag event and run a workflow that tags it on the monorepo? I think the commit happens first and then you tag it. Therefore the commit got the old tag?

Also, does that mean that commits are constantly retagged to the latest tag? 🤔

**Comment by TomasVotruba** [comment]
It might help. Could you test your idea?

> Also, does that mean that commits are constantly retagged to the latest tag? thinking

It's possible. Could you verify this?

**Comment by ruudk** [comment]
~I see that you fixed it, right?~

Hmm, no, these 2 run at the same time:
https://github.com/symplify/github-actions/runs/1508148735?check_suite_focus=true
https://github.com/symplify/github-actions/runs/1508148492?check_suite_focus=true

**Comment by TomasVotruba** [comment]
See the issue: https://github.com/WyriHaximus/github-action-get-previous-tag/issues/9

The main discussion is there. All commit trials are based on it

**Comment by TomasVotruba** [comment]
One way or another, the new relase is there :)
https://github.com/symplify/monorepo-split-github-action/releases/tag/0.1.3

I'll keep investigating how to make split working

**Comment by ruudk** [comment]
Thanks for the tag :)
