### ISSUE TITLE
localize-composer-paths requires COMPOSER_ROOT_VERSION: "dev-master" but my branch is `main`

### ISSUE THREAD

**Issue by ruudk** [symplify/github-actions#4]
I'm implementing a monorepo split for LongRunning. The root branch is called `main` instead of `master`. But somehow I need to specify `COMPOSER_ROOT_VERSION: "dev-master"`

https://github.com/LongRunning/LongRunning/blob/main/.github/workflows/tests.yaml#L6

Any idea how to solve this?

**Comment by ruudk** [comment]
This issue should be moved to https://github.com/symplify/symplify

**Comment by TomasVotruba** [comment]
Closing as moved
